### 登录
POST http://localhost:8081/user/login HTTP/1.1
Content-Type: application/json;charset=UTF-8

{"username":"banzhu","password":"banzhu"}

### 注册
POST http://localhost:8081/user/register HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "username":"345678",
    "password":"345678",
    "rePassword":"345678",
    "nickname":"345678",
    "bir":"2019-02-24",
    "sex":"1"
}

### 登出
GET http://localhost:8081/user/loginOut HTTP/1.1
ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxIiwiZXhwIjoxNTgyNzQwMTY4LCJpYXQiOjE1ODI3MzY1Njh9.yeJzeqqeZIyCuiw9RbsrewUD0S6DwVqz4ezyPeqtU5U

### 列表
POST http://localhost:8081/weibo/listAll HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
    "pageIndex":1,
    "pageSize":3
}

### 查找用户
POST http://localhost:8081/user/search HTTP/1.1
ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIxIiwiZXhwIjoxNTgyNzQwMTY4LCJpYXQiOjE1ODI3MzY1Njh9.yeJzeqqeZIyCuiw9RbsrewUD0S6DwVqz4ezyPeqtU5U
Content-Type: application/json;charset=UTF-8

{
    "pageIndex":1,
    "pageSize":3,
    "query":"测试"
}

### 查找微博
POST http://localhost:8081/weibo/search HTTP/1.1
ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyIiwiZXhwIjoxNTgzNjY1MTQ5LCJpYXQiOjE1ODM2NjE1NDl9.vCY1-80nMIxyf4c-oSWP9uEZYwcVyRKeoGYinAiBIPk
Content-Type: application/json;charset=UTF-8

{
    "pageIndex":1,
    "pageSize":3,
    "query":"",
    "topic":"#二手交易# "
}

### 消息列表
POST http://localhost:8081/message/query HTTP/1.1
ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzIiwiZXhwIjoxNTgzNjgzNjg0LCJpYXQiOjE1ODM2ODAwODR9.yoACD02eLOe-1NWCIDI04jSF7G2uX06Ddc7S_G1BBWc
Content-Type: application/json;charset=UTF-8

{
    "pageIndex":1,
    "pageSize":3,
    "messageType":0,
    "messageId":0
}

### 系统公告
POST http://localhost:8081/message/systemNotice HTTP/1.1
ACCESS_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIzIiwiZXhwIjoxNTgzNjgzNjg0LCJpYXQiOjE1ODM2ODAwODR9.yoACD02eLOe-1NWCIDI04jSF7G2uX06Ddc7S_G1BBWc
Content-Type: application/json;charset=UTF-8

{
    "content":"45555"
}